"""Customer service for property search and advice functionality."""
import json
import requests
from datetime import datetime
from app.models import CustomerEnquiry, LLMConfig

# Import OpenAI
try:
    import openai
    OPENAI_AVAILABLE = True
except ImportError:
    OPENAI_AVAILABLE = False


class CustomerService:
    """Service class for customer property operations."""
    
    @staticmethod
    def search_properties(search_criteria):
        """Search properties using web search (placeholder implementation)."""
        # This is a placeholder implementation
        # In a real application, you would integrate with property APIs like 99acres
        
        location = search_criteria.get('location', '')
        property_type = search_criteria.get('property_type', '')
        budget_min = search_criteria.get('budget_min', 0)
        budget_max = search_criteria.get('budget_max', 0)
        
        # Mock property results
        mock_results = [
            {
                'id': 1,
                'title': f'Beautiful {property_type} in {location}',
                'location': location,
                'price': budget_min + 500000 if budget_min else 5000000,
                'area': '1200 sq ft',
                'bedrooms': 2 if property_type == '2BHK' else 3,
                'bathrooms': 2,
                'description': f'Spacious {property_type} apartment with modern amenities',
                'image_url': 'https://via.placeholder.com/300x200',
                'contact': '+91-9876543210'
            },
            {
                'id': 2,
                'title': f'Premium {property_type} in {location}',
                'location': location,
                'price': budget_max - 200000 if budget_max else 7500000,
                'area': '1500 sq ft',
                'bedrooms': 3 if property_type == '3BHK' else 2,
                'bathrooms': 3,
                'description': f'Luxury {property_type} with premium finishes',
                'image_url': 'https://via.placeholder.com/300x200',
                'contact': '+91-9876543211'
            }
        ]
        
        return mock_results
    
    @staticmethod
    def get_property_advice(advice_request):
        """Get property advice using OpenAI LLM."""
        # Get active LLM configuration
        llm_config = LLMConfig.get_active_config()
        
        if not llm_config:
            return "LLM configuration not found. Please contact administrator to configure OpenAI settings."
        
        if not llm_config.api_key:
            return "OpenAI API key not configured. Please contact administrator to set up the API key."
        
        if not OPENAI_AVAILABLE:
            return "OpenAI library not installed. Please install the openai package to use LLM features."
        
        try:
            # Initialize OpenAI client
            client = openai.OpenAI(api_key=llm_config.api_key)
            
            # Create a comprehensive system prompt for property advisory
            system_prompt = """You are an expert real estate advisor for ONC REALTY PARTNERS, a premium property advisory firm in India. 
            
Your expertise includes:
- Indian real estate market trends and regulations
- Property investment strategies
- Legal compliance (RERA, stamp duty, registration)
- Location analysis and infrastructure development
- Home loan processes and financial planning
- Property valuation and market analysis

Guidelines for responses:
- Provide practical, actionable advice
- Consider Indian market conditions and regulations
- Include specific recommendations when possible
- Mention legal compliance requirements
- Be professional yet approachable
- Ask clarifying questions when needed
- Provide structured responses with clear sections

Always prioritize customer safety and legal compliance in your recommendations."""

            # Create user prompt with context
            user_prompt = f"""Property Advisory Request: {advice_request}

Please provide comprehensive property advice addressing the customer's query. Include relevant market insights, legal considerations, financial planning tips, and actionable next steps where applicable."""

            # Make API call to OpenAI
            response = client.chat.completions.create(
                model=llm_config.model_name or "gpt-3.5-turbo",
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt}
                ],
                max_tokens=1000,
                temperature=0.7,
                top_p=1.0,
                frequency_penalty=0.0,
                presence_penalty=0.0
            )
            
            # Extract the advice from the response
            advice = response.choices[0].message.content.strip()
            
            # Add a professional footer
            advice += "\n\n---\n*This advice is generated by ONC REALTY PARTNERS' AI advisory system. For personalized consultation, please contact our expert team.*"
            
            return advice
            
        except openai.AuthenticationError as e:
            return "Invalid OpenAI API key. Please contact administrator to verify the API key configuration."
        
        except openai.RateLimitError as e:
            return "OpenAI API rate limit exceeded. Please try again in a few minutes or contact administrator."
        
        except openai.APIError as e:
            return f"OpenAI API error: {str(e)}. Please try again or contact administrator."
        
        except Exception as e:
            # Log the error for debugging (keep minimal logging)
            print(f"Error in get_property_advice: {str(e)}")
            
            # Fallback to mock response if OpenAI fails
            return CustomerService._get_fallback_advice(advice_request)
    
    @staticmethod
    def _get_fallback_advice(advice_request):
        """Fallback advice when OpenAI is not available."""
        if 'investment' in advice_request.lower():
            return """**Investment Advisory (Fallback Mode)**

Based on your investment query, here are key recommendations:

1. **Location Analysis**: Focus on areas with upcoming infrastructure development
2. **Property Type**: 2BHK and 3BHK apartments offer better rental yields
3. **Budget Planning**: Allocate 70-80% for property, 20-30% for additional costs
4. **Legal Verification**: Verify RERA registration and clear title
5. **Market Timing**: Current conditions favor investment with stable prices

*Note: This is a fallback response. For AI-powered personalized advice, please ensure OpenAI API is properly configured.*"""
        
        elif 'first home' in advice_request.lower() or 'buying' in advice_request.lower():
            return """**First Home Buyer Guide (Fallback Mode)**

Congratulations on planning your first home purchase!

1. **Financial Planning**: EMI should not exceed 40% of monthly income
2. **Location Priorities**: Consider commute, amenities, and connectivity
3. **Legal Checklist**: RERA registration, clear title, approved plans
4. **Home Loan**: Compare rates and consider pre-approval
5. **Future Value**: Research resale potential and area development

*Note: This is a fallback response. For AI-powered personalized advice, please ensure OpenAI API is properly configured.*"""
        
        else:
            return f"""**Property Advisory (Fallback Mode)**

Thank you for your inquiry: "{advice_request}"

General recommendations:
1. Research local market trends and pricing
2. Verify all legal documents and RERA registration
3. Plan finances including additional costs
4. Consider location connectivity and amenities
5. Consult with local real estate experts

*Note: This is a fallback response. For AI-powered personalized advice, please ensure OpenAI API is properly configured in the admin panel.*"""
    
    @staticmethod
    def generate_report(customer_id, enquiry_ids):
        """Generate comprehensive property report."""
        try:
            # Get customer enquiries
            enquiries = CustomerEnquiry.query.filter(
                CustomerEnquiry.customer_id == customer_id,
                CustomerEnquiry.id.in_(enquiry_ids)
            ).all()
            
            if not enquiries:
                return "No enquiries found for report generation."
            
            # Generate report content
            report = f"""
PROPERTY SEARCH & ADVISORY REPORT
Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
Customer ID: {customer_id}

=== SUMMARY ===
Total Enquiries: {len(enquiries)}
Search Requests: {len([e for e in enquiries if e.enquiry_type == 'search'])}
Advice Requests: {len([e for e in enquiries if e.enquiry_type == 'advice'])}

=== DETAILED ENQUIRIES ===
"""
            
            for i, enquiry in enumerate(enquiries, 1):
                report += f"\n{i}. ENQUIRY #{enquiry.id} ({enquiry.enquiry_type.upper()})\n"
                report += f"   Date: {enquiry.created_at.strftime('%Y-%m-%d %H:%M:%S')}\n"
                
                if enquiry.enquiry_type == 'search':
                    if enquiry.search_criteria:
                        criteria = json.loads(enquiry.search_criteria)
                        report += f"   Search Criteria: {criteria}\n"
                
                elif enquiry.enquiry_type == 'advice':
                    if enquiry.advice_request:
                        report += f"   Request: {enquiry.advice_request[:100]}...\n"
                    if enquiry.llm_response:
                        report += f"   Advice: {enquiry.llm_response[:200]}...\n"
                
                report += "\n"
            
            report += """
=== RECOMMENDATIONS ===
Based on your enquiries, here are our key recommendations:

1. Continue researching properties in your preferred locations
2. Consider consulting with our real estate experts for personalized guidance
3. Keep track of market trends and price movements
4. Ensure all legal verifications before making any purchase decisions
5. Plan your finances including additional costs beyond property price

For further assistance, please contact our support team.

---
This report is generated automatically based on your enquiry history.
For detailed consultation, please schedule an appointment with our experts.
"""
            
            return report
            
        except Exception as e:
            return f"Error generating report: {str(e)}"
    @staticmethod
    def generate_text_report(customer_id, enquiry_ids=None, report_type='comprehensive'):
        """Generate text-based report as fallback when PDF is not available."""
        try:
            from app.models import CustomerEnquiry
            import json
            from datetime import datetime
            
            # Get customer enquiries
            query = CustomerEnquiry.query.filter_by(customer_id=customer_id)
            
            if enquiry_ids:
                query = query.filter(CustomerEnquiry.id.in_(enquiry_ids))
            
            if report_type == 'search-only':
                query = query.filter_by(enquiry_type='search')
            elif report_type == 'advice-only':
                query = query.filter_by(enquiry_type='advice')
            
            enquiries = query.order_by(CustomerEnquiry.created_at.desc()).all()
            
            if not enquiries:
                return "No enquiries found for report generation."
            
            # Generate text report
            report = f"""
ONC REALTY PARTNERS - PROPERTY SEARCH & ADVISORY REPORT
Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
Customer ID: {customer_id}
Report Type: {report_type.replace('-', ' ').title()}

=== SUMMARY ===
Total Enquiries: {len(enquiries)}
Search Requests: {len([e for e in enquiries if e.enquiry_type == 'search'])}
Advice Requests: {len([e for e in enquiries if e.enquiry_type == 'advice'])}

=== DETAILED ENQUIRIES ===
"""
            
            for i, enquiry in enumerate(enquiries, 1):
                report += f"\n{i}. ENQUIRY #{enquiry.id} - {enquiry.enquiry_type.upper()}\n"
                report += f"   Date: {enquiry.created_at.strftime('%Y-%m-%d %H:%M:%S')}\n"
                
                if enquiry.enquiry_type == 'search' and enquiry.search_criteria:
                    try:
                        criteria = json.loads(enquiry.search_criteria)
                        report += f"   Location: {criteria.get('location', 'N/A')}\n"
                        report += f"   Property Type: {criteria.get('property_type', 'Any')}\n"
                        if criteria.get('budget_min'):
                            report += f"   Budget: ₹{criteria['budget_min']:,} - ₹{criteria.get('budget_max', 0):,}\n"
                    except:
                        report += "   Search criteria not available\n"
                
                elif enquiry.enquiry_type == 'advice':
                    if enquiry.advice_request:
                        report += f"   Request: {enquiry.advice_request[:100]}...\n"
                    if enquiry.llm_response:
                        report += f"   Advice: {enquiry.llm_response[:200]}...\n"
                
                report += "\n"
            
            report += """
=== RECOMMENDATIONS ===
1. Continue researching properties in your preferred locations
2. Consider consulting with our real estate experts
3. Plan your finances including additional costs
4. Ensure all legal verifications before purchase
5. Stay informed about market trends

Thank you for choosing ONC REALTY PARTNERS!
"""
            
            return report
            
        except Exception as e:
            return f"Error generating text report: {str(e)}"